name: Build Push

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build and push Docker image
        run: |
          source .env
          for dir in */; do
            version=${dir%/}
            if [[ $version =~ ^[0-9]+\.[0-9]+$ ]]; then
              if [ -f "$version/Dockerfile" ]; then
                docker build \
                  -f $version/Dockerfile \
                  --build-arg TIMEZONE=$TIMEZONE \
                  -t build/${REPOSITORY}:${version} .
              fi
            fi
          done
          for dir in */; do
            version=${dir%/}
            if [[ $version =~ ^[0-9]+\.[0-9]+$ ]]; then
              if [ -f "$version/Dockerfile" ]; then
                docker run -d --name smash_img build/${REPOSITORY}:${version}
                docker export smash_img > /tmp/docker-smash_img.tar
                docker import /tmp/docker-smash_img.tar smash_latest
                docker build \
                    -f Dockerfile.smash \
                    --build-arg SMASH_IMG=smash_latest \
                    -t ${REGISTRY}/${REPOSITORY}:${version} .
                docker push ${REGISTRY}/${REPOSITORY}:${version}
                rmI smash_latest
                rmI build/${REPOSITORY}:${version}
                rm /tmp/docker-smash_img.tar
              fi
            fi
          done
        shell: bash


